name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"
on:
 push:
   branches:
   - main

 
env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
 
   steps:
     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
     - run: pwd && ls

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0
    
     - name: Terraform init
       id: init
       run: terraform init 


     - name: Terraform apply
       id: apply
       run: terraform apply --auto-approve 
